apiVersion: v1
kind: Service
metadata:
  labels:
    app: nfs-server-svc-ext
  name: nfs-server-svc-ext
  namespace: nfs
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs-server-ext
  type: LoadBalancer